### PR TITLE
Update generate.md to include warnings in generation process

### PR DESCRIPTION
**Pull request by Tennessene**
I have edited a couple of parts on the page of the website about generation. I have added a warning about the issue when cloning the latest version of the gir-files repo and mentioned to create a new issue if the user is having problems when creating bindings for other libraries. These could make the experience for the user better.

### CODE REVIEW

**Comment by badcel** [comment]
@jwharm did you consider adding the gir-files as a git submodule? Then if your repository is cloned the Gir files are cloned automatically with the commit specified in your repository. This would ensure users have always a known good version of the Gir files.

**Comment by jwharm** [comment]
@Tennessene Thanks for the PR, but the website won’t update until the CI build works again.

Someday I will replace the site with a Github wiki.

**Comment by jwharm** [comment]
> @jwharm did you consider adding the gir-files as a git submodule? Then if your repository is cloned the Gir files are cloned automatically with the commit specified in your repository. This would ensure users have always a known good version of the Gir files.

I thought those were difficult to get right.

**Comment by Tennessene** [comment]
> @Tennessene Thanks for the PR, but the website won’t update until the CI build works again.
> 
> Someday I will replace the site with a Github wiki.

So should I close this then?

**Comment by jwharm** [comment]
@Tennessene Please keep it open for now.

**Pull request closed without merging**
