### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by JFronny**
Automatically publish to GitHub packages using the code provided [here](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#publishing-packages-to-github-packages).
Whenever a release is created, the action is run and a stable package is uploaded. On every push, a -SNAPSHOT package is uploaded.
Javadocs and sources are uploaded as well.
Ideally, releases would (also) be published to maven central once panama is GA and 1.0 is reached.
I'm personally not a huge fan of using gradlew in repositories, but set up the wrapper-validation-action to verify its authenticity. If you don't want to use it, I'll switch back to using system gradle (currently, half of the wrapper is there, but the jar is missing, so I added it)
This PR depends on #11, so it's currently a draft.
If you want to merge this, I'll squash the commits and remove the `actions` branch from the list of branches to execute this on, which I added to test the action.

### CODE REVIEW

**Comment by jwharm** [comment]
I’ve added you as collaborator to the repository. Feel free to merge this and any future PRs to main.

**Comment by jwharm** [comment]
Seeing the CI in action is really cool!

**Comment by jwharm** [comment]
I'd like to publish a 0.3 release within the next few weeks. I mostly want to cleanup some code, add missing javadoc, and hopefully find a solution for #20. Can I just create a release on github or do I need to do anything special for the CI?

After the 0.3 release, I'd like to look at adding convenience API for deriving custom types.
And also update to JDK20 EA - the Panama API's have been changed (again) including the replacement of `MemoryAddress` so that will require some rework.

**Comment by JFronny** [comment]
Just creating a release without any artifacts should run the script, which should then build and upload the artifacts (though they currently won't be added to the release automatically)
When experimenting with GTK builds for https://github.com/jwharm/java-gi/tree/windows-support, I noticed that manual pipelines can take inputs and create releases, to which they can upload artifacts, so I could probably move the entire logic for that to the script as well, if that is desirable.

**Pull request merged**
