### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by JFronny**
Just some random things that stood out to me
- format javadocs: start with lowercase
- convert a few comments to javadocs
- make lookup tables in `Conversions` final (and act on them directly in `JavaGI`/`CrossReference`)
- make `BindingsGenerator` static
- use `javagi$ensureInitialized` in `Interop` instead of manually loading
- Rename `Build` to `Builder` and add `public static Builder builder()` method to instantiate
- prefix `String`, `Object`, `Builder` classes with `Gi` to avoid conflicts. Not really happy with this one, do you have suggestions?
- move `GTypeDefinitions`/`GValueCreator` to patches
- use enum for alias target types
- introduce `InteropException` instead of unspecific `RuntimeException`
- pass constructor to Pointers instead of finding it via reflection
- make a few public methods in abstract classes protected

### CODE REVIEW

**Review by jwharm — APPROVED** [review]
Nice improvements. Some of these cleanups were long overdue.

I wanted to use `Builder` instead of `Build` but it caused some nasty conflicts with the Gtk Builder class. So that's why I used `Build`. By renaming the GTK `Builder` to `GiBuilder`, the problem is solved.

I don't really like the `Gi` prefix either, but I don't know a better fitting prefix. (An alternative solution would be to use simpler package names, like 'glib' and 'gtk', but it's really bad practice to not use reverse domain names.)

**Comment by JFronny** [comment]
I could suffix the class name with something like _ or $ instead of using a prefix

**Comment by jwharm** [comment]
I prefer `GiObject` over `Object$` or `Object_`, but it’s subjective.

**Comment by JFronny** [comment]
I think theres some potential for confusion between GObject and GiObject.
But if you are fine with this I'll merge it. 
Merging into `callbacks` requires some changes, but I have a local branch for those

**Comment by jwharm** [comment]
What if we name them `GObject`, `GString` and `GtkBuilder`? We can put the global constants and functions into that class.

**Comment by JFronny** [comment]
Adding a `G` prefix would work, yes (That would make GtkBuilder GBuilder, but that's preferable to special casing the Gtk, imo).
Doing that for GObject would need quite a bit of special casing for GObject, so maybe adding a suffix to the static GObject class would be better.

**Comment by jwharm** [comment]
The `G` prefix is specified in the `c:identifier-prefixes` attribute of the namespace. I’ll see if I can use that to set the prefix (and add a suffix to the classes with the static globals).

**Comment by jwharm** [comment]
I spent a few hours yesterday on some different approaches, but eventually settled on:
- Use the namespace as a prefix (`GObject`, `GString`, `GtkBuilder`)
- Renamed the old `GObject` class to `GObjects`

**Comment by JFronny** [comment]
`GObjects` is nice

**Pull request merged**
