### PR TITLE
Implement signal emission

### PR DESCRIPTION
**Pull request by JFronny**
This reuses the methods in Parameters, so signalSource parameters are not omitted.

### CODE REVIEW

**Comment by jwharm** [comment]
Great idea, and pairs very nicely with the signal handlers.

One issue:
Many signals have a return value (usually a `boolean`) and in that case, according to the [doc](https://docs.gtk.org/gobject/func.signal_emit_by_name.html), a pointer to a memory location for the return value must be appended to the varargs.

And a suggestion, but not must-have:
I'm wondering if you could implement this with a call to the already generated Java function `GObjects.signalEmitByName`. It avoids duplicate code for the parameter marshalling, and you don't need to declare the downcall handle in the Interop class.

**Comment by JFronny** [comment]
It *could* be implemented with GObjects.signalEmitByName, but that wouldn't remove the duplication of the biggest components, namely the memory session and exception handling, since those are also needed for additional parameters (the varargs of GObjects.signalEmitByName are passed to Panama directly, so they must be converted by the caller). I didn't like the idea of doing that (especially having two memory sessions for the same method call), so I went with this approach, which also does the method call in the generated code and thereby avoids this duplication.

**Comment by jwharm** [comment]
OK, true.

**Comment by jwharm** [comment]
By the way, I would expect that varargs are marshalled automatically, I added `Interop.unwrapJavagiTypes` for that, and I'm pretty sure that works for strings and GValues (primitive aliases) at the very least.

**Comment by JFronny** [comment]
Things like arrays, which are used as signal parameters in some cases, aren't supported by Interop.unwrapJavagiTypes, though.

**Comment by JFronny** [comment]
To test the result processing, I tried the following code, but it segfaults for some reason.
```java
window.onCloseRequest(() -> true);
System.out.println(window.emitCloseRequest(window));
```

**Comment by jwharm** [comment]
I think the signal source shouldn't be passed to `g_signal_emit_by_name` as part of the varargs array. I've pushed a very quick and dirty fix to omit the signal source, and now the window `close-request` emission works.

The root cause is that this parameter should not even be there anyway: Some time ago I've artificially added it to the parameter list (see [Signal.java](https://github.com/jwharm/java-gi/blob/28b3cd24c62e53ddaff046c952d509d5b87f2ca8/generator/src/main/java/io/github/jwharm/javagi/model/Signal.java#L25-L34)) but I should probably refactor the entire signal handler functionality so that insertion isn't necessary anymore.

**Comment by jwharm** [comment]
> Things like arrays, which are used as signal parameters in some cases, aren't supported by Interop.unwrapJavagiTypes, though.

Then that's a bug :-)

**Comment by jwharm** [comment]
Commit [782be6d](https://github.com/jwharm/java-gi/commit/782be6d16305866e0685316c518eabef9dba67aa) changes the handling of the signal source parameter. It is not prepended to the signal parameter list anymore. I also removed the quick fix from the previous commit.

The effect is that the `emit` methods have no useless `source` parameter anymore.

Incidentally, this uncovered a name clash with the already existing method `TlsConnection.emitAcceptCertificate`. So I added a check (copied from `Field` generator) to avoid this.

**Comment by JFronny** [comment]
> > Things like arrays, which are used as signal parameters in some cases, aren't supported by Interop.unwrapJavagiTypes, though.
> 
> Then that's a bug :-)

Since `allocateNativeArray` must know whether the array should be zero-terminated, and checking for callbacks is not possible (since interfaces can't override functions and abstract classes can't be `FunctionalInterface`s, the only way to do this would be with reflection) supporting all types here is not possible.
Support for Pointer types could be added, but that wouldn't fix support in most cases.
While a mid-way solution could be achieved (IE most types are unwrapped at runtime and some at compile time), that would require the duplication of a lot of code, so I don't think it really is superior to the current implementation.
Given that, this should be OK, right?

**Comment by jwharm** [comment]
Yes it's OK to merge.
I logged the varargs problem as a separate issue (#44).

**Pull request merged**
